# Generated by Django 3.2.6 on 2021-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='token',
            field=models.CharField(default='BasicToken-6f0ce962-c8f5-4a5c-bfff-a84f375b613969da34d5-7773-495d-9856-187b8f83d473', max_length=200),
        ),
    ]
